server:
  port: 8080

logging:
  path: logs/app.log
  file: mylog.log

spring:
  application:
    name:myTest
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      username: root
      password: qwe123

mybatis:
  type-aliases-package: com.course.model
  mapper-locations: classpath:mapper/*.xml

